.github/ISSUE_TEMPLATE/deprecate-sgid-dataset-or-web-application.md

feat: add action taken and initials

---

.github/ISSUE_TEMPLATE/introduce-sgid-dataset.md

Here's a draft to hack on for data creation steps.

feat: add introduction template

---

.github/ISSUE_TEMPLATE/introduce-sgid-dataset.md

Could be nice to specify the intended ISO category for the new data set.

Update Summary Section - add ISO category

---

.github/ISSUE_TEMPLATE/introduce-sgid-dataset.md

we should verify that sweeper and the metadata are returning no issues before adding the data to the sgid or anywhere. I think this is a good place to validate that. Thoughts? 
Feel free to tag others. I'm not sure wants to review these changes.

don't forget about data quality

---

README.md

docs: add sgid data flow information for new datasets

---

.coveragerc
.travis.yml
.vscode/settings.json
Dockerfile
pylintrc
setup.py
src/conductor/checks.py
src/conductor/conductor.py
src/conductor/connection_sample.py
src/conductor/server.py
src/readme.md
tests/test_checks.py
tests/test_conductor.py

the read me is a little random but otherwise I think this will be working once the VPC is accessible. Let's merge once the VPC has been tested etc. Also the tests need fixing.

modifications to deploy and run in GCP

---

.github/ISSUE_TEMPLATE/deprecate-sgid-dataset-or-web-application.md
.github/ISSUE_TEMPLATE/introduce-sgid-dataset.md
.vscode/settings.json
src/conductor/checks.py
src/conductor/conductor.py
src/conductor/connections_sample.py
src/conductor/server.py
src/readme.md
tests/data/triage_issue_body_all_completed.txt
tests/data/triage_issue_body_strikethrough.txt
tests/data/triage_issue_body_uncompleted.txt
tests/test_checks.py
tests/test_conductor.py
tests/test_triage_checker.py

TODO:
Would love to know if this is headed in the right direction...
Closes #56

Triage checker

---

.github/ISSUE_TEMPLATE/deprecate-sgid-dataset-or-web-application.md

feat: add team drive reminder

---

.github/workflows/ci.yml

try to use less run times for non conductor related events.

refactor(conductor): filter runs to conductor dir

---

src/conductor/checks.py
src/conductor/conductor.py
tests/data/tasks_issue_body_mock_simple.txt
tests/test_conductor.py
tests/test_task_checker.py

Output from test run for current issues:

Fixes for the task checker in conductor

---

.coveragerc
src/conductor/conductor.py
tests/test_conductor.py

it's not longer accessible.
We should update the secrets also to remove the old connection.

remove sgid10 conductor check

---

.github/ISSUE_TEMPLATE/2-deprecate-sgid-dataset.md

the intent of this pr to add the soft delete process to the template, "removing data from the SGID".  See what you think.

Update deprecation process

---

.github/ISSUE_TEMPLATE/2-deprecate-sgid-dataset.md

make the sgid index piece more explicate

Update soft delete wording

---

.github/ISSUE_TEMPLATE/2-deprecate-sgid-dataset.md

chore: remove backseat driver reference

---

.github/workflows/google.yml
src/cloud-run-deployment.yml

this won't run in dev without a tag. I suppose we could use rc tags or something or we could use an if: github.event_name or action or something == tag to run prod and let dev run on push.

Add cloud run creation to the action

---

.github/ISSUE_TEMPLATE/2-deprecate-sgid-dataset.md

Ref: https://www.esri.com/arcgis-blog/products/arcgis-living-atlas/announcements/a-process-for-deprecating-maps-and-layers/
This is just to get the conversation going. I'm not sure that we need to add all of these steps...

feat: incorporate ideas from recent AGOL blog post

---

src/conductor/checks.py

Otherwise, recent edits may not show up in the checks.
Ref: https://github.com/agrc/porter/issues/163#issuecomment-981845629

fix: point at versioned view of meta table

---

.github/ISSUE_TEMPLATE/1-introduce-sgid-dataset.md
.github/ISSUE_TEMPLATE/2-deprecate-sgid-dataset.md
.github/ISSUE_TEMPLATE/3-deprecate-application.md
.github/ISSUE_TEMPLATE/5-deprecate-empty.md

fix: update default year to 2022

---

.github/ISSUE_TEMPLATE/1-introduce-sgid-dataset.md

this doc is a reminder on what not to forget when adding new data to the sgid.

add google drive link to template on how to add table to internal sgid 

---

.github/ISSUE_TEMPLATE/3-deprecate-application.md

feat: add action item for APM in ServiceNow

---

.github/ISSUE_TEMPLATE/2-deprecate-sgid-dataset.md

add check box for database layers
alter wording
add and change hyperlinks

change path to deprecation backup location

---

.github/ISSUE_TEMPLATE/2-deprecate-sgid-dataset.md

update ng911 point of contact

---

.github/ISSUE_TEMPLATE/2-deprecate-sgid-dataset.md

ensure there is a path forward if the layer is in the base maps

add base maps check to remove template

---

.github/ISSUE_TEMPLATE/1-introduce-sgid-index-dataset.yaml
.github/ISSUE_TEMPLATE/2-introduce-sgid-on-arcgis-dataset.yaml
.github/ISSUE_TEMPLATE/3-introduce-open-sgid-dataset.yaml
.github/ISSUE_TEMPLATE/4-introduce-sgid-dataset.md
.github/ISSUE_TEMPLATE/5-introduce-application.md
.github/ISSUE_TEMPLATE/6-deprecate-sgid-dataset.md
.github/ISSUE_TEMPLATE/7-deprecate-application.md
.github/ISSUE_TEMPLATE/8-deprecate-empty.md

replace greg with hank on the 911 stuff
replace greg with zach on the data-team checks

replace greg in the issue templates

---

.github/ISSUE_TEMPLATE/6-deprecate-sgid-dataset.md

Changed "sgidStatus" to "indexStatus" in template to match column name in SGID Index spreadsheet.

fix: indexStatus column name

---

.github/ISSUE_TEMPLATE/4-introduce-sgid-dataset.md
.github/ISSUE_TEMPLATE/5-introduce-application.md
.github/ISSUE_TEMPLATE/6-deprecate-sgid-dataset.md
.github/ISSUE_TEMPLATE/7-deprecate-application.md
.github/ISSUE_TEMPLATE/8-deprecate-empty.md
tests/data/tasks_issue_body_mock_strikethrough.txt

- update year
- update data team coordinator
- update urls

Update the templates for 2025 🍾🍾🍾

---

.github/ISSUE_TEMPLATE/4-introduce-sgid-dataset.md
.github/ISSUE_TEMPLATE/5-introduce-application.md

feat: add moonwalk backup steps

---

src/conductor/conductor.py

correct report label
